version: 0.2

 

phases:
install:
runtime-versions:
golang: 1.14
build:
commands:
- echo Building the Go code...
- go build hello.go
artifacts: "arn:aws:s3:::codepipeline-ap-south-1-614365726039/MyArtifact"
secondary-artifacts:
golang_artifacts:
base-directory: GoTraining
files:
- hello
